# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Souvik Dey"
resume_title:                   "Senior Staff SDET @Druva"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "souvik.dey.etce@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91-7276447317"
resume_contact_address:         "Pune, MH-411045"

resume_header_contact_info:     "Pune, MH-411045 • 7276447317 • souvik.dey.etce@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Experienced SDET adept in bringing forth expertise in problem-solving, developing, testing, and maintenance of software test automation frameworks. Proficient in an assortment of technologies, including python, linux, selenium, AWS, Linux, API Automation. Able to effectively self-manage during independent projects, lead groups of people as well as collaborate as part of a productive team.   </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/SouvikDcoder"
  resume_twitter_url:           "https://twitter.com/itsviciz"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/souvik-d-ey/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
